// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/agreements" | "/admin/agreements/[id]" | "/admin/alerts" | "/admin/attendance" | "/admin/audit-log" | "/admin/automations" | "/admin/briefing" | "/admin/build-tracker" | "/admin/bulk-import" | "/admin/clients" | "/admin/clients/[id]" | "/admin/clients/[id]/reports/new" | "/admin/clients/renewals" | "/admin/data-management" | "/admin/duplicates" | "/admin/finance" | "/admin/finance/expenses" | "/admin/finance/gst" | "/admin/finance/invoices" | "/admin/finance/pnl" | "/admin/financials" | "/admin/growth" | "/admin/growth/acquisition" | "/admin/growth/acquisition/[city]" | "/admin/growth/facebook" | "/admin/growth/gmb" | "/admin/growth/instagram" | "/admin/growth/linkedin" | "/admin/growth/seo" | "/admin/leads/[id]" | "/admin/leads/[id]/proposal/[proposalId]/agreement" | "/admin/leads/[id]/proposal/new" | "/admin/marketing" | "/admin/meetings" | "/admin/niche-kits" | "/admin/operations" | "/admin/outreach" | "/admin/outreach/pdf-log" | "/admin/proposals" | "/admin/reports" | "/admin/sales" | "/admin/sales/leads" | "/admin/sessions" | "/admin/settings" | "/admin/strategy" | "/admin/strategy/archive" | "/admin/strategy/review" | "/admin/team" | "/admin/team/scorecards" | "/admin/team/sops" | "/admin/team/sops/[id]" | "/admin/team/sops/new" | "/admin/upload" | "/admin/upload/debug" | "/admin/upload/history" | "/admin/users" | "/admin/whatsapp-templates" | "/admin/work-hours" | "/attendance" | "/client-portal/[id]" | "/client/dashboard" | "/client/report/[token]" | "/login" | "/lp/[niche]/[city]" | "/manager/performance" | "/manager/pipeline" | "/projects" | "/projects/[id]" | "/projects/list" | "/sales" | "/sales/leads/[id]" | "/sales/outreach" | "/sales/pitch/[industry]/[city]" | "/staff" | "/strategist" | "/strategist/deals" | "/tasks" | "/tasks/list" | "/telecaller" | "/telecaller/my-stats"
type AppRouteHandlerRoutes = "/api/attendance/break" | "/api/attendance/clock-in" | "/api/attendance/clock-out" | "/api/cron/admin-alerts" | "/api/cron/automations/followups" | "/api/cron/automations/sla" | "/api/cron/automations/tasks" | "/api/cron/daily-digest" | "/api/cron/session-timeout" | "/api/cron/sla" | "/api/export" | "/api/inbound/[channel]" | "/api/leads/duplicates/scan" | "/api/leads/merge" | "/api/leads/merge/undo" | "/api/notifications/verify" | "/api/public/client-report/[token]" | "/api/reports/sessions/export.csv" | "/api/reports/work-hours" | "/api/session/end" | "/api/session/ping" | "/api/session/start" | "/api/webhooks/whatsapp"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/agreements": {}
  "/admin/agreements/[id]": { "id": string; }
  "/admin/alerts": {}
  "/admin/attendance": {}
  "/admin/audit-log": {}
  "/admin/automations": {}
  "/admin/briefing": {}
  "/admin/build-tracker": {}
  "/admin/bulk-import": {}
  "/admin/clients": {}
  "/admin/clients/[id]": { "id": string; }
  "/admin/clients/[id]/reports/new": { "id": string; }
  "/admin/clients/renewals": {}
  "/admin/data-management": {}
  "/admin/duplicates": {}
  "/admin/finance": {}
  "/admin/finance/expenses": {}
  "/admin/finance/gst": {}
  "/admin/finance/invoices": {}
  "/admin/finance/pnl": {}
  "/admin/financials": {}
  "/admin/growth": {}
  "/admin/growth/acquisition": {}
  "/admin/growth/acquisition/[city]": { "city": string; }
  "/admin/growth/facebook": {}
  "/admin/growth/gmb": {}
  "/admin/growth/instagram": {}
  "/admin/growth/linkedin": {}
  "/admin/growth/seo": {}
  "/admin/leads/[id]": { "id": string; }
  "/admin/leads/[id]/proposal/[proposalId]/agreement": { "id": string; "proposalId": string; }
  "/admin/leads/[id]/proposal/new": { "id": string; }
  "/admin/marketing": {}
  "/admin/meetings": {}
  "/admin/niche-kits": {}
  "/admin/operations": {}
  "/admin/outreach": {}
  "/admin/outreach/pdf-log": {}
  "/admin/proposals": {}
  "/admin/reports": {}
  "/admin/sales": {}
  "/admin/sales/leads": {}
  "/admin/sessions": {}
  "/admin/settings": {}
  "/admin/strategy": {}
  "/admin/strategy/archive": {}
  "/admin/strategy/review": {}
  "/admin/team": {}
  "/admin/team/scorecards": {}
  "/admin/team/sops": {}
  "/admin/team/sops/[id]": { "id": string; }
  "/admin/team/sops/new": {}
  "/admin/upload": {}
  "/admin/upload/debug": {}
  "/admin/upload/history": {}
  "/admin/users": {}
  "/admin/whatsapp-templates": {}
  "/admin/work-hours": {}
  "/api/attendance/break": {}
  "/api/attendance/clock-in": {}
  "/api/attendance/clock-out": {}
  "/api/cron/admin-alerts": {}
  "/api/cron/automations/followups": {}
  "/api/cron/automations/sla": {}
  "/api/cron/automations/tasks": {}
  "/api/cron/daily-digest": {}
  "/api/cron/session-timeout": {}
  "/api/cron/sla": {}
  "/api/export": {}
  "/api/inbound/[channel]": { "channel": string; }
  "/api/leads/duplicates/scan": {}
  "/api/leads/merge": {}
  "/api/leads/merge/undo": {}
  "/api/notifications/verify": {}
  "/api/public/client-report/[token]": { "token": string; }
  "/api/reports/sessions/export.csv": {}
  "/api/reports/work-hours": {}
  "/api/session/end": {}
  "/api/session/ping": {}
  "/api/session/start": {}
  "/api/webhooks/whatsapp": {}
  "/attendance": {}
  "/client-portal/[id]": { "id": string; }
  "/client/dashboard": {}
  "/client/report/[token]": { "token": string; }
  "/login": {}
  "/lp/[niche]/[city]": { "niche": string; "city": string; }
  "/manager/performance": {}
  "/manager/pipeline": {}
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/projects/list": {}
  "/sales": {}
  "/sales/leads/[id]": { "id": string; }
  "/sales/outreach": {}
  "/sales/pitch/[industry]/[city]": { "industry": string; "city": string; }
  "/staff": {}
  "/strategist": {}
  "/strategist/deals": {}
  "/tasks": {}
  "/tasks/list": {}
  "/telecaller": {}
  "/telecaller/my-stats": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
