// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/agreements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agreements/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/agreements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/agreements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agreements">> = Specific
  const handler = {} as typeof import("../../../app/admin/agreements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/alerts">> = Specific
  const handler = {} as typeof import("../../../app/admin/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/attendance">> = Specific
  const handler = {} as typeof import("../../../app/admin/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit-log">> = Specific
  const handler = {} as typeof import("../../../app/admin/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/automations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/automations">> = Specific
  const handler = {} as typeof import("../../../app/admin/automations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/briefing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/briefing">> = Specific
  const handler = {} as typeof import("../../../app/admin/briefing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/build-tracker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/build-tracker">> = Specific
  const handler = {} as typeof import("../../../app/admin/build-tracker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/bulk-import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bulk-import">> = Specific
  const handler = {} as typeof import("../../../app/admin/bulk-import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/clients/[id]/reports/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients/[id]/reports/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/clients/[id]/reports/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients">> = Specific
  const handler = {} as typeof import("../../../app/admin/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/clients/renewals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients/renewals">> = Specific
  const handler = {} as typeof import("../../../app/admin/clients/renewals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/data-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data-management">> = Specific
  const handler = {} as typeof import("../../../app/admin/data-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/duplicates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/duplicates">> = Specific
  const handler = {} as typeof import("../../../app/admin/duplicates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/expenses">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/gst/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/gst">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/gst/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/invoices">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/finance/pnl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/pnl">> = Specific
  const handler = {} as typeof import("../../../app/admin/finance/pnl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/financials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/financials">> = Specific
  const handler = {} as typeof import("../../../app/admin/financials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/acquisition/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/acquisition/[city]">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/acquisition/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/acquisition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/acquisition">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/acquisition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/facebook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/facebook">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/facebook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/gmb/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/gmb">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/gmb/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/instagram/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/instagram">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/instagram/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/linkedin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/linkedin">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/linkedin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/growth/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/seo">> = Specific
  const handler = {} as typeof import("../../../app/admin/growth/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/leads/[id]/proposal/[proposalId]/agreement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads/[id]/proposal/[proposalId]/agreement">> = Specific
  const handler = {} as typeof import("../../../app/admin/leads/[id]/proposal/[proposalId]/agreement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/leads/[id]/proposal/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads/[id]/proposal/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/leads/[id]/proposal/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/marketing">> = Specific
  const handler = {} as typeof import("../../../app/admin/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/meetings">> = Specific
  const handler = {} as typeof import("../../../app/admin/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/niche-kits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/niche-kits">> = Specific
  const handler = {} as typeof import("../../../app/admin/niche-kits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/operations">> = Specific
  const handler = {} as typeof import("../../../app/admin/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/outreach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/outreach">> = Specific
  const handler = {} as typeof import("../../../app/admin/outreach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/outreach/pdf-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/outreach/pdf-log">> = Specific
  const handler = {} as typeof import("../../../app/admin/outreach/pdf-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/proposals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/proposals">> = Specific
  const handler = {} as typeof import("../../../app/admin/proposals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/sales/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sales/leads">> = Specific
  const handler = {} as typeof import("../../../app/admin/sales/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sales">> = Specific
  const handler = {} as typeof import("../../../app/admin/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sessions">> = Specific
  const handler = {} as typeof import("../../../app/admin/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/strategy/archive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/strategy/archive">> = Specific
  const handler = {} as typeof import("../../../app/admin/strategy/archive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/strategy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/strategy">> = Specific
  const handler = {} as typeof import("../../../app/admin/strategy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/strategy/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/strategy/review">> = Specific
  const handler = {} as typeof import("../../../app/admin/strategy/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team">> = Specific
  const handler = {} as typeof import("../../../app/admin/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/team/scorecards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team/scorecards">> = Specific
  const handler = {} as typeof import("../../../app/admin/team/scorecards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/team/sops/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team/sops/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/team/sops/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/team/sops/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team/sops/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/team/sops/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/team/sops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/team/sops">> = Specific
  const handler = {} as typeof import("../../../app/admin/team/sops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/upload/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/upload/debug">> = Specific
  const handler = {} as typeof import("../../../app/admin/upload/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/upload/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/upload/history">> = Specific
  const handler = {} as typeof import("../../../app/admin/upload/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/upload">> = Specific
  const handler = {} as typeof import("../../../app/admin/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/whatsapp-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp-templates">> = Specific
  const handler = {} as typeof import("../../../app/admin/whatsapp-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/work-hours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/work-hours">> = Specific
  const handler = {} as typeof import("../../../app/admin/work-hours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance">> = Specific
  const handler = {} as typeof import("../../../app/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client-portal/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client-portal/[id]">> = Specific
  const handler = {} as typeof import("../../../app/client-portal/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/client/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/client/report/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/report/[token]">> = Specific
  const handler = {} as typeof import("../../../app/client/report/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/lp/[niche]/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lp/[niche]/[city]">> = Specific
  const handler = {} as typeof import("../../../app/lp/[niche]/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/manager/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/performance">> = Specific
  const handler = {} as typeof import("../../../app/manager/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/manager/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manager/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/manager/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/list">> = Specific
  const handler = {} as typeof import("../../../app/projects/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sales/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../app/sales/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sales/outreach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/outreach">> = Specific
  const handler = {} as typeof import("../../../app/sales/outreach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../../app/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sales/pitch/[industry]/[city]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/pitch/[industry]/[city]">> = Specific
  const handler = {} as typeof import("../../../app/sales/pitch/[industry]/[city]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../app/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/strategist/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategist/deals">> = Specific
  const handler = {} as typeof import("../../../app/strategist/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/strategist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/strategist">> = Specific
  const handler = {} as typeof import("../../../app/strategist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tasks/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/list">> = Specific
  const handler = {} as typeof import("../../../app/tasks/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../../app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/telecaller/my-stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecaller/my-stats">> = Specific
  const handler = {} as typeof import("../../../app/telecaller/my-stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/telecaller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telecaller">> = Specific
  const handler = {} as typeof import("../../../app/telecaller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/break/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/break">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/break/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/clock-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/clock-in">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/clock-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attendance/clock-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attendance/clock-out">> = Specific
  const handler = {} as typeof import("../../../app/api/attendance/clock-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/admin-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/admin-alerts">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/admin-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/automations/followups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/automations/followups">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/automations/followups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/automations/sla/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/automations/sla">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/automations/sla/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/automations/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/automations/tasks">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/automations/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/daily-digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-digest">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/daily-digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/session-timeout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/session-timeout">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/session-timeout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/sla/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sla">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/sla/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export">> = Specific
  const handler = {} as typeof import("../../../app/api/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inbound/[channel]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inbound/[channel]">> = Specific
  const handler = {} as typeof import("../../../app/api/inbound/[channel]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/duplicates/scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/duplicates/scan">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/duplicates/scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/merge">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/leads/merge/undo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/merge/undo">> = Specific
  const handler = {} as typeof import("../../../app/api/leads/merge/undo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/client-report/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/client-report/[token]">> = Specific
  const handler = {} as typeof import("../../../app/api/public/client-report/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/sessions/export.csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/sessions/export.csv">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/sessions/export.csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/work-hours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/work-hours">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/work-hours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/session/end/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/end">> = Specific
  const handler = {} as typeof import("../../../app/api/session/end/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/session/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/ping">> = Specific
  const handler = {} as typeof import("../../../app/api/session/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/session/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/start">> = Specific
  const handler = {} as typeof import("../../../app/api/session/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/whatsapp">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
