/**
 * sync_bot_kb.mjs
 *
 * Reads the 6 KB files from 00_MASTER/Bot_Knowledge_Base/ and regenerates
 * lib/bot/kb.ts as exported string constants.
 *
 * Run whenever the KB changes:
 *   node scripts/sync_bot_kb.mjs
 *
 * The generated file is committed — Vercel gets the inlined version with
 * zero runtime filesystem dependency.
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dir = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(__dir, "..");
const kbRoot = resolve(appRoot, "../../00_MASTER/Bot_Knowledge_Base");

const FILES = [
  { key: "KB_COMPANY",      file: "company.md" },
  { key: "KB_SERVICES",     file: "services.md" },
  { key: "KB_PRICING",      file: "pricing.md" },
  { key: "KB_FAQS",         file: "faqs.md" },
  { key: "KB_OBJECTIONS",   file: "objections.md" },
  { key: "KB_GUARDRAILS",   file: "guardrails_and_escalation.md" },
];

function escape(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const exports = FILES.map(({ key, file }) => {
  const content = readFileSync(resolve(kbRoot, file), "utf8").trim();
  return `export const ${key} = \`\n${escape(content)}\n\`;`;
});

const fullSystemPrompt = FILES.map(({ key }) => `\${${key}}`).join("\n\n---\n\n");

const out = `// AUTO-GENERATED by scripts/sync_bot_kb.mjs
// Source: 00_MASTER/Bot_Knowledge_Base/
// Run "node scripts/sync_bot_kb.mjs" to regenerate after KB edits.
// DO NOT EDIT MANUALLY.

${exports.join("\n\n")}

/**
 * Full system prompt — all 6 KB files concatenated in the canonical order.
 * Pass this as the \`system\` field in the Anthropic API call.
 */
export const KB_SYSTEM_PROMPT = \`You are the FortuneMarq AI assistant. You answer questions and help leads book a free call with Jabeer (the founder). You ONLY represent FortuneMarq — stay on-topic.

Below is your complete knowledge base. Follow it exactly. Never invent facts, services, prices, or client results not listed here.

${fullSystemPrompt}

---

BEHAVIOUR RULES (override everything else):
- Your PRIMARY goal: answer the lead's question clearly, then steer toward booking a free 15-min call with Jabeer.
- You CAN book the meeting yourself — if the lead agrees, ask for their preferred day and time, then confirm you'll set it up.
- Never quote a price outside pricing.md. If asked for a discount or custom bundle → say "Let me connect you with Jabeer directly — he can work through the numbers with you."
- Never guarantee results.
- Match the lead's language — English or Kannada/Kanglish.
- Keep messages short (2–4 sentences max) unless a detailed answer is clearly needed.
- End most replies with a soft next-step question or booking offer.
\`;
`;

const outPath = resolve(appRoot, "lib/bot/kb.ts");
writeFileSync(outPath, out, "utf8");
console.log(`✓ lib/bot/kb.ts regenerated (${FILES.length} KB files inlined)`);
FILES.forEach(({ key, file }) => {
  const lines = readFileSync(resolve(kbRoot, file), "utf8").split("\n").length;
  console.log(`  ${key} ← ${file} (${lines} lines)`);
});
